steps:
  # Step 1: Build Frontend
  - name: 'node:lts'
    id: 'Build Frontend'
    dir: 'frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install --legacy-peer-deps
        npm run build

  # Step 2: Prepare Backend
  - name: 'node:lts'
    id: 'Prepare Backend'
    dir: 'backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        mkdir -p public
        cp -r ../frontend/dist/* public/

  # Step 3: Deploy to Cloud Run (No env vars here)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'crm-fullstack-portal'     # ✅ Change to your desired service name
      - '--source'
      - './backend'
      - '--region'
      - 'asia-south1'              # ✅ Same as your DB
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
