options:
  logging: CLOUD_LOGGING_ONLY  # ✅ Fix for logs bucket error

steps:
  - name: 'node:lts'
    id: Build Frontend
    entrypoint: bash
    args:
      - -c
      - |
        npm ci
        npm run build

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy to Cloud Run
    entrypoint: gcloud
    args:
      - run
      - deploy
      - crm-fullstack-portal-v2   # ✅ change this name
      - --source=.
      - --region=asia-south1
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars
      - PORT=5000
