version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mydb
    restart: always
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mybackend
    environment:
      DB_HOST: db # Very important! Use the 'db' service name, not 'localhost'
      DB_USER: user
      DB_PASS: password
      DB_NAME: testdb
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
